syntax = "proto3";

package monadiam.kafka.access_cache.v1;

message AccessCacheValue {
    AccessCacheTopicAction action_type = 1;
    AccessCachePayload payload = 2;
}

enum AccessCacheTopicAction {
    INVALIDATE = 0;
}

message AccessCachePayload {
    repeated AccessCacheItem items = 1;
}

message AccessCacheItem {
    InvalidationScope scope = 1;
    optional string account = 2;
    optional string realm = 3;
}

enum InvalidationScope {
    ACCOUNT_REALM = 0;
    ACCOUNT = 1;
    GLOBAL = 2;
    REALM = 3;
}
