syntax = "proto3";

package monadiam.kafka.interface_client.v1;

message InterfaceClientValue {
    InterfaceClientTopicAction action_type = 1;
    InterfaceClientPayload payload = 2;
}

enum InterfaceClientTopicAction {
    CREATE = 0;
    REVOKE = 1;
    RESTORE = 2;
    PURGE = 3;
}

message InterfaceClientPayload {
    string actor = 1;
    string realm = 2;
    InterfaceClientInput input = 3;
}

message InterfaceClientInput {
    string application = 1;
    bool is_revoked = 2;
    string id = 3;
}
