syntax = "proto3";

package monadiam.kafka.notification.v1;

message NotificationValue {
    NotificationTopicAction action_type = 1;
    NotificationPayload payload = 2;
}

enum NotificationTopicAction {
    CREATE = 0;
    CANCEL = 1;
}

message NotificationPayload {
    optional string actor = 1;
    optional string realm = 2;
    NotificationInput input = 3;
}

message NotificationInput {
    optional NotificationContentKind kind = 1;
    optional string recipient = 2;
    optional NotificationCategory category = 3;
    optional PlatformService source_service = 4;
    optional string dedup_key = 5;
    optional string title = 6;
    optional string text = 7;
    optional MessageTemplate template = 8;
    optional string language = 9;
    map<string, string> params = 10;
    optional NotificationPayload override = 11;
}

enum NotificationContentKind {
    TEMPLATE = 0;
    CONTENT = 1;
}

enum NotificationCategory {
    SECURITY = 0;
    INVITES = 1;
    SYSTEM = 2;
    OTHER = 3;
}

enum MessageTemplate {
    IDENTIFIER_VERIFICATION_OTP = 0;
    ACCOUNT_VERIFICATION_OTP = 1;
    RESET_PASSWORD_OTP = 2;
    LOGIN_OTP = 3;
    PASSWORD_CHANGED_VIA_RECOVERY_CODE = 4;
    PASSWORD_CHANGED_VIA_OTP = 5;
    PASSWORD_CHANGED = 6;
    SECOND_FACTOR_ENABLED = 7;
    SECOND_FACTOR_RESET = 8;
    RECOVERY_CODES_REGENERATED = 9;
    IDENTIFIER_PURGED = 10;
    LOGIN_ALERT = 11;
    INVITE_RECEIVED = 12;
    INVITE_CANCELLED = 13;
    ASSIGNMENT_GRANTED = 14;
    ASSIGNMENT_REVOKED = 15;
    REALM_EXCLUDED = 16;
}

enum PlatformService {
    ACCESS_CONTROL_SERVICE = 0;
    NOTIFICATION_SERVICE = 1;
    CERTIFICATE_SERVICE = 2;
    IDENTITY_SERVICE = 3;
}
