name: CI Checks (Parallel)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            ghcr.io/gitleaks/gitleaks:v8.24.2 \
            git /repo --config /repo/.gitleaks.toml --verbose

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install -g npm@11.6.2
          npm ci

      - name: Run TSC
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --quiet

      - name: Run Knip
        run: npm run knip

  build:
    runs-on: ubuntu-latest
    needs: [static-analysis]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.17.0"
          cache: "npm"
      - run: npm ci
      - run: npm run build
